// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"database/sql"
)

type Folder struct {
	ID          int64
	Path        string
	Name        string
	Description sql.NullString
	User        int64
	Public      sql.NullBool
}

type Link struct {
	ID          int64
	Url         string
	Name        sql.NullString
	Description sql.NullString
	Folder      int64
}

type User struct {
	ID   int64
	Name string
	Uuid interface{}
}
